### ISSUE TITLE
Stalled Torrent?

### ISSUE THREAD

**Issue by kalbasit** [albertrdixon/docker-transmission#4]
Why do you remove stalled torrent? This just cost me about 200Gb of lost data :(

```
[15/01/2016 13:48:35] [torrent_cleaner] INFO: Running torrent cleaner
[15/01/2016 13:48:35] [torrent_cleaner] INFO: Torrent #1 ('xxx') reporting stalled.
[15/01/2016 13:48:35] [torrent_cleaner] INFO: Torrent #1 ('xxx') being removed because it is stalled (Stalled: True, Status:
downloading)
```

is there another way of doing this?

**Comment by a-lagopus** [comment]
Hi,
this might come in a little late, and I have to mention - I'm completely unrelated to the developer.
I think there's a workaround to your issue.

The stalled torrent is removed due to the torrent_cleaner script, which apparently is the respected @albertrdixon 's attempt to automate transmission.
To work around it, it's possible to never put torrents in "stale" state in the first place:

The file in the container /transmission/settings.json should be a line:
queue-stalled-enabled:true ([source](https://trac.transmissionbt.com/wiki/EditConfigFiles))
Changing it to false should do the trick. I didn't encounter this myself, so this is not tested.

Hope that helps

**Comment by albertrdixon** [comment]
Ahhhh, that sucks :(
I admit that this transmission is fairly customized for my needs. I generally am using some manager like Sickrage or Couchpotato to handle torrents, so I want stalled torrents to be ejected so the manager will go find a different copy. If you do not want that behavior, you can set the following environment variable: `ENABLE_CLEANER=false`

**Comment by kalbasit** [comment]
Oh, I see now, and it's indeed quite useful.

I just finished building [transmission-torrent-cleaner](https://github.com/kalbasit/transmission-torrent-cleaner) based on this idea as a separate binary. However, it allows the user infinite ways of protecting a torrent. Given that transmission has no concept of tags, I'm using the DownloadDir as a way of separating torrents added manually from the ones added by SickRage.

**Comment by albertrdixon** [comment]
@kalbasit right on RE: your transmission-torrent-cleaner. Looks pretty cool!

Going to close this issue out.
